version: "3.6"
services:

  php:
    image: containers.fgtclb.com/fes-cp/tools-php8.1:v3
    environment:
      - TYPO3_INSTALL_DB_DRIVER=mysqli
      - TYPO3_INSTALL_DB_USER=typo3
      - TYPO3_INSTALL_DB_PASSWORD=typo3
      - TYPO3_INSTALL_DB_HOST=mysql-db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_DBNAME=typo3
      - TYPO3_INSTALL_DB_USE_EXISTING=y
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_PASSWORD=password
      - TYPO3_INSTALL_SITE_NAME=fgtclb/http-api integration test
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
      - COMPOSER_HOME=/tmp/.composer/
    volumes:
      - ".:/var/www/"
      - "$HOME/.composer:/tmp/.composer"

  mysql-db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    environment:
      - MYSQL_PASSWORD=typo3
      - MYSQL_DATABASE=typo3
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=typo3
    networks:
      default:
        aliases:
          - "mysql.${HOST}"
    volumes:
      - "./.docker/mysql:/docker-entrypoint-initdb.d"
